language: node_js
nodejs:
  - lts/*

services:
  - docker

before_install:
  - docker build -t thomas2400/reactapp -f Dockerfile . #. refer to current directory

script:
  - docker run thomas2400/reactapp npm run test -- --coverage